-- MariaDB schema definition for the turnos system
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('ADMIN','ASESOR','MATRIZADOR') NOT NULL,
    display_name VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tickets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    client_name VARCHAR(150) NOT NULL,
    client_identifier VARCHAR(50) NOT NULL,
    motive VARCHAR(255) NOT NULL,
    client_type ENUM('GENERAL','TERCERA_EDAD','DISCAPACITADO') NOT NULL DEFAULT 'GENERAL',
    service_type ENUM('TRAMITE','ASESORIA') NOT NULL DEFAULT 'TRAMITE',
    priority BOOLEAN NOT NULL DEFAULT 0,
    status ENUM('PENDING','ASSIGNED','IN_PROGRESS','DONE') NOT NULL DEFAULT 'PENDING',
    assigned_to INT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_ticket_user FOREIGN KEY (assigned_to) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS agent_states (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    status ENUM('FREE','BUSY') NOT NULL DEFAULT 'FREE',
    current_ticket_id INT NULL,
    CONSTRAINT fk_agent_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_agent_ticket FOREIGN KEY (current_ticket_id) REFERENCES tickets(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
